export const siteConfig = {
  githubUsername: "sprakhar11",
  email: "prakhar.infinity@gmail.com",
  linkedin: "sprakhar07",
  twitter: "",
  name: "Prakhar Sharma",
  role: "Software Development Engineer",
  description: "I love to architect scalable systems from scratch, building robust APIs, optimizing databases, and ensuring secure data flow across complex architectures.",
  showSkills: true,
  showExperience: true,
  showAchievements: true,
  showProjects: true,
  showContact: true,
  enableEmailService: true,
  enableResumeDownload: true,
};
